version: 3

tasks:
  build:
    desc: Build
    cmds:
      - go mod download
      - go mod tidy
      - go build ./...

  dependencyUpdates:
    desc: Show dependency updates
    cmds:
      - go mod download
      - go mod tidy
      - go list -u -m -json all | go-mod-outdated -update -direct
